//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proteinOceanVis2022.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tarikDBEntitiesEv : DbContext
    {
        public tarikDBEntitiesEv()
            : base("name=tarikDBEntitiesEv")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminTable> adminTable { get; set; }
        public virtual DbSet<sepetTable> sepetTable { get; set; }
        public virtual DbSet<urunTable> urunTable { get; set; }
        public virtual DbSet<uyeTable> uyeTable { get; set; }
    }
}
